### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by sha-lala** [CCSoleil/latent_graph_atsc#4]
作者你好，对您的工作很感兴趣，非常希望您能把您的代码开源

**Comment by zeeeyang** [comment]
You can send me an email.  I will email you. Thanks.

**Comment by sha-lala** [comment]
作者您好，最近在阅读Inducing Target-Specific Latent Structures for Aspect Sentiment Classification这篇文章，我觉得这篇论文思路很好，不知您是否可以将源程序发给我，数据集及其相关的必要信息。我保证它们只会用于研究目的。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCSoleil/latent_graph_atsc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月13日(星期六) 晚上10:48
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCSoleil/latent_graph_atsc] 代码 (Issue #4)





 
You can send me an email.  I will email you. Thanks.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
