### ISSUE TITLE
对你们的工作很感兴趣，请问代码还开源吗

### ISSUE THREAD

**Issue by fangchuanml** [CCSoleil/latent_graph_atsc#5]
Hey, 

Thanks for your attention.  We will release it after next ACL submission.

_Originally posted by @zeeeyang in https://github.com/CCSoleil/latent_graph_atsc/issues/1#issuecomment-747265594_

**Comment by zeeeyang** [comment]
Sure. Thanks for your interest.

**Comment by zeeeyang** [comment]
I already send you the codes via  email. Thanks.
